### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by Mohagames205** [jasonwynn10/Pen#5]
The plugin does not load I get this error:

```
[15:52:13] [Server thread/INFO]: Loading Pen v1.0.0
[15:52:13] [Server thread/CRITICAL]: pocketmine\resourcepacks\ResourcePackException: "Encountered ZipArchive error code 9 while trying to open phar:///home/container/plugins/Pen (2).phar/resources/PenPlugin.mcpack" (EXCEPTION) in "src/pocketmine/resourcepacks/ZippedResourcePack" at line 88
[15:52:13] [Server thread/DEBUG]: #0 plugins/Pen (2).phar/src/jasonwynn10/Pen/Main(25): pocketmine\resourcepacks\ZippedResourcePack->__construct(string phar:///home/container/plugins/Pen (2).phar/resources/PenPlugin.mcpack)
[15:52:13] [Server thread/DEBUG]: #1 src/pocketmine/plugin/PluginManager(193): jasonwynn10\Pen\Main->onLoad()
[15:52:13] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(343): pocketmine\plugin\PluginManager->loadPlugin(string /home/container/plugins/Pen (2).phar, array Array())
[15:52:13] [Server thread/DEBUG]: #3 src/pocketmine/Server(1715): pocketmine\plugin\PluginManager->loadPlugins(string /home/container/plugins/)
[15:52:13] [Server thread/DEBUG]: #4 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/container/, string /home/container/plugins/)
[15:52:13] [Server thread/DEBUG]: #5 (1): require(string phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[15:52:13] [Server thread/CRITICAL]: Could not load plugin 'Pen'
```

I am running the latest version of Pocketmine.

**Comment by xXRyzen** [comment]
Same

**Comment by jasonw4331** [comment]
what platform is the server running on? Also, what PocketMine Version are you using?

**Comment by xXRyzen** [comment]
Running on Linux, PocketMine-MP 3.8.2 for Minecraft: Bedrock Edition v1.11.0

**Comment by jasonw4331** [comment]
Is your error message exactly the same?

**Comment by xXRyzen** [comment]
Exactly the same yes

**Comment by jasonw4331** [comment]
I've just released a new update. Can you please test with it?

**Comment by xXRyzen** [comment]
Ill test now

**Comment by xXRyzen** [comment]
Same issue using latest build from poggit

**Comment by Mohagames205** [comment]
Hi, I am also still getting the same issue. I am running Pocketmine 3.8.5 and it's running on Windows 10 1903.
